apiVersion: v1
kind: Pod
metadata:
  name: myproject
  labels:
    app: myproject
spec:
  containers:
  - image: jponte84/concourse-tutorial-hello-world:%%imageversion%%
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: myproject
  restartPolicy: Always
