apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: myproject-deployment
  labels:
    app: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      containers:
      - name: myproject
        image: jponte84/concourse-tutorial-hello-world
        ports:
        - containerPort: 80
