resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.15"

resources:
- name: jar-project
  type: git
  source:
    branch: master
    uri: https://github.com/jponte84/MyProject.git

- name: hello-world-docker-image
  type: docker-image
  source:
    email: jponte84@gmail.com
    username: jponte84
    password: ((docker.password))
    repository: jponte84/concourse-tutorial-hello-world

- name: version
  type: semver
  source:
    initial_version: 0.0.1
    uri: https://jponte84:((git.password))@github.com/jponte84/MyProject.git
    branch: master
    file: version
    driver: git

- name: k8s
  type: kubernetes
  source:
    kubeconfig: ((kubeconfig))

jobs:
- name: build-jar
  public: true
  serial: true
  plan:
  - get: jar-project
    trigger: false
  - get: version
    params: {bump: patch}

  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
      inputs:
        - name: jar-project
        - name: version
      outputs:
        - name: jar-project-output
      run:
        path: sh
        args:
        - -exc
        - |
          export VERSION=$(cat version/number) 
          cd jar-project
          mvn versions:set -DnewVersion=${VERSION}
          mvn package
          cp docker/Dockerfile ../jar-project-output
          cp target/*.jar ../jar-project-output
  
  - put: hello-world-docker-image
    params:
      build: jar-project-output
      tag: version/number
  - put: version
    params: {file: version/number}

- name: deploy-k8s
  public: true
  plan: 
    - get: jar-project
      trigger: false
    - get: version
    - get: hello-world-docker-image
      trigger: true
      passed:
        - "build-jar"

    - task: change-version
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: busybox
        inputs:
        - name: version
        - name: jar-project
        outputs:  
        - name: jar-project-out        
        run:
          path: sh
          args:
          - -exc
          - |
            sed -i -e 's/\%%imageversion%%/'$(cat version/number)'/g' jar-project/k8s/deployment.yaml
            cd jar-project
            cat k8s/deployment.yaml
            cp k8s/deployment.yaml ../jar-project-out
            

    - put: k8s
      params:
        kubectl: apply -f jar-project-out/deployment.yaml
        wait_until_ready: 60
